import pyttsx3
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice',voices[1].id)
engine.say('Good Morning Sudha')
engine.say('Which company are you going today')
engine.say('Vbj')
engine.say('Akshaya')
engine.say('Badmaraj')
engine.runAndWait()
